/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as JoinRouteImport } from './routes/join'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoutinePulseRouteImport } from './routes/_authenticated/routine-pulse'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedGardenRouteImport } from './routes/_authenticated/garden'
import { Route as AuthenticatedFormsRouteImport } from './routes/_authenticated/forms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedBrandEssenceRouteImport } from './routes/_authenticated/brand-essence'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiStripeCallbackRouteImport } from './routes/api/stripe/callback'
import { Route as ApiFormsSubmitRouteImport } from './routes/api/forms/submit'
import { Route as ApiDonationsCheckoutRouteImport } from './routes/api/donations/checkout'

const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutinePulseRoute =
  AuthenticatedRoutinePulseRouteImport.update({
    id: '/routine-pulse',
    path: '/routine-pulse',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGardenRoute = AuthenticatedGardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormsRoute = AuthenticatedFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandEssenceRoute =
  AuthenticatedBrandEssenceRouteImport.update({
    id: '/brand-essence',
    path: '/brand-essence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCallbackRoute = ApiStripeCallbackRouteImport.update({
  id: '/api/stripe/callback',
  path: '/api/stripe/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormsSubmitRoute = ApiFormsSubmitRouteImport.update({
  id: '/api/forms/submit',
  path: '/api/forms/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationsCheckoutRoute = ApiDonationsCheckoutRouteImport.update({
  id: '/api/donations/checkout',
  path: '/api/donations/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/enroll': typeof EnrollRoute
  '/join': typeof JoinRoute
  '/partner': typeof PartnerRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/brand-essence': typeof AuthenticatedBrandEssenceRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/garden': typeof AuthenticatedGardenRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/routine-pulse': typeof AuthenticatedRoutinePulseRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/donations/checkout': typeof ApiDonationsCheckoutRoute
  '/api/forms/submit': typeof ApiFormsSubmitRoute
  '/api/stripe/callback': typeof ApiStripeCallbackRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/enroll': typeof EnrollRoute
  '/join': typeof JoinRoute
  '/partner': typeof PartnerRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/brand-essence': typeof AuthenticatedBrandEssenceRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/garden': typeof AuthenticatedGardenRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/routine-pulse': typeof AuthenticatedRoutinePulseRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/donations/checkout': typeof ApiDonationsCheckoutRoute
  '/api/forms/submit': typeof ApiFormsSubmitRoute
  '/api/stripe/callback': typeof ApiStripeCallbackRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/enroll': typeof EnrollRoute
  '/join': typeof JoinRoute
  '/partner': typeof PartnerRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/brand-essence': typeof AuthenticatedBrandEssenceRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRoute
  '/_authenticated/garden': typeof AuthenticatedGardenRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/routine-pulse': typeof AuthenticatedRoutinePulseRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/donations/checkout': typeof ApiDonationsCheckoutRoute
  '/api/forms/submit': typeof ApiFormsSubmitRoute
  '/api/stripe/callback': typeof ApiStripeCallbackRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/enroll'
    | '/join'
    | '/partner'
    | '/analytics'
    | '/brand-essence'
    | '/community'
    | '/dashboard'
    | '/forms'
    | '/garden'
    | '/onboarding'
    | '/routine-pulse'
    | '/settings'
    | '/api/donations/checkout'
    | '/api/forms/submit'
    | '/api/stripe/callback'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/enroll'
    | '/join'
    | '/partner'
    | '/analytics'
    | '/brand-essence'
    | '/community'
    | '/dashboard'
    | '/forms'
    | '/garden'
    | '/onboarding'
    | '/routine-pulse'
    | '/settings'
    | '/api/donations/checkout'
    | '/api/forms/submit'
    | '/api/stripe/callback'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/enroll'
    | '/join'
    | '/partner'
    | '/_authenticated/analytics'
    | '/_authenticated/brand-essence'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/forms'
    | '/_authenticated/garden'
    | '/_authenticated/onboarding'
    | '/_authenticated/routine-pulse'
    | '/_authenticated/settings'
    | '/api/donations/checkout'
    | '/api/forms/submit'
    | '/api/stripe/callback'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EnrollRoute: typeof EnrollRoute
  JoinRoute: typeof JoinRoute
  PartnerRoute: typeof PartnerRoute
  ApiDonationsCheckoutRoute: typeof ApiDonationsCheckoutRoute
  ApiFormsSubmitRoute: typeof ApiFormsSubmitRoute
  ApiStripeCallbackRoute: typeof ApiStripeCallbackRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routine-pulse': {
      id: '/_authenticated/routine-pulse'
      path: '/routine-pulse'
      fullPath: '/routine-pulse'
      preLoaderRoute: typeof AuthenticatedRoutinePulseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garden': {
      id: '/_authenticated/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof AuthenticatedGardenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brand-essence': {
      id: '/_authenticated/brand-essence'
      path: '/brand-essence'
      fullPath: '/brand-essence'
      preLoaderRoute: typeof AuthenticatedBrandEssenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/callback': {
      id: '/api/stripe/callback'
      path: '/api/stripe/callback'
      fullPath: '/api/stripe/callback'
      preLoaderRoute: typeof ApiStripeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forms/submit': {
      id: '/api/forms/submit'
      path: '/api/forms/submit'
      fullPath: '/api/forms/submit'
      preLoaderRoute: typeof ApiFormsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations/checkout': {
      id: '/api/donations/checkout'
      path: '/api/donations/checkout'
      fullPath: '/api/donations/checkout'
      preLoaderRoute: typeof ApiDonationsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBrandEssenceRoute: typeof AuthenticatedBrandEssenceRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRoute
  AuthenticatedGardenRoute: typeof AuthenticatedGardenRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRoutinePulseRoute: typeof AuthenticatedRoutinePulseRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBrandEssenceRoute: AuthenticatedBrandEssenceRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFormsRoute: AuthenticatedFormsRoute,
  AuthenticatedGardenRoute: AuthenticatedGardenRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRoutinePulseRoute: AuthenticatedRoutinePulseRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EnrollRoute: EnrollRoute,
  JoinRoute: JoinRoute,
  PartnerRoute: PartnerRoute,
  ApiDonationsCheckoutRoute: ApiDonationsCheckoutRoute,
  ApiFormsSubmitRoute: ApiFormsSubmitRoute,
  ApiStripeCallbackRoute: ApiStripeCallbackRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
